module.exports = {
  'parser': 'babel-eslint',
  'env': {
    'node': true,
    'es6': true
  },
  'plugins': [
    'react',
  ],
  'rules': {
    'array-bracket-spacing': 2,
    'camelcase': [2, { 'properties': 'never' }],
    'comma-dangle': [1, 'never'],
    'comma-spacing': [2, { 'before': false, 'after': true }],
    'comma-style': [2, 'last'],
    'constructor-super': 2,
    'eol-last': 2,
    'indent': [2, 2],
    'key-spacing': [2, { 'beforeColon': false, 'afterColon': true }],
    'max-depth': [2, 4],
    'max-len': [2, 120, 4],
    'max-params': [2, 4],
    'max-statements': [2, 10],
    'no-confusing-arrow': 2,
    'no-bitwise': 2,
    'no-class-assign': 2,
    'no-const-assign': 2,
    'no-dupe-class-members': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-multiple-empty-lines': [2, { 'max': 2, 'maxEOF': 1 }],
    'no-nested-ternary': 2,
    'no-new-object': 2,
    'no-this-before-super': 2,
    'no-trailing-spaces': 2,
    'object-shorthand': [2, 'always'],
    'prefer-const': 2,
    'semi': [2, 'always'],

    'jsx-quotes': 1,
    'react/forbid-prop-types': 1,
    'react/jsx-boolean-value': 1,
    'react/jsx-closing-bracket-location': 1,
    'react/jsx-curly-spacing': [1, 'always'],
    'react/jsx-indent-props': 1,
    'react/jsx-max-props-per-line': 2,
    'react/jsx-no-bind': 1,
    'react/jsx-no-duplicate-props': 1,
    'react/jsx-no-undef': 1,
    'react/jsx-sort-props': 1,
    'react/jsx-uses-react': 1,
    'react/jsx-uses-vars': 1,
    'react/no-danger': 1,
    'react/no-did-mount-set-state': 1,
    'react/no-did-update-set-state': 1,
    'react/no-direct-mutation-state': 1,
    'react/no-multi-comp': 1,
    'react/no-unknown-property': 1,
    'react/prefer-es6-class': 1,
    'react/prop-types': 1,
    'react/react-in-jsx-scope': 1,
    'react/require-extension': 1,
    'react/self-closing-comp': 1,
    'react/sort-comp': 1,
    'react/sort-prop-types': 1,
    'react/wrap-multilines': 1,
  },
};
