module.exports = {
  'parser': 'babel-eslint',
  'env': {
    'node': true,
    'es6': true
  },
  'plugins': [
    'react',
    'import'
  ],
  'rules': {
    'array-bracket-spacing': 2,
    'brace-style': [2, '1tbs', { 'allowSingleLine': true }],
    'camelcase': [2, { 'properties': 'never' }],
    'comma-dangle': [1, 'never'],
    'comma-spacing': [2, { 'before': false, 'after': true }],
    'comma-style': [2, 'last'],
    'constructor-super': 2,
    'eol-last': 2,
    'indent': [2, 2],
    'jsx-quotes': 2,
    'key-spacing': [2, { 'beforeColon': false, 'afterColon': true }],
    'max-depth': [2, 4],
    'max-len': [2, 120, 4],
    'max-params': [2, 4],
    'max-statements': [2, 10],
    'no-bitwise': 2,
    'no-class-assign': 2,
    'no-cond-assign': [2, 'always'],
    'no-confusing-arrow': 2,
    'no-const-assign': 2,
    'no-constant-condition': 2,
    'no-dupe-class-members': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-extra-bind': 2,
    'no-extra-boolean-cast': 2,
    'no-fallthrough': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-multi-spaces': 2,
    'no-multiple-empty-lines': [2, { 'max': 1 }],
    'no-nested-ternary': 2,
    'no-new-object': 2,
    'no-redeclare': 2,
    'no-self-assign': 2,
    'no-sequences': 2,
    'no-sparse-arrays': 2,
    'no-this-before-super': 2,
    'no-trailing-spaces': 2,
    'no-unexpected-multiline': 2,
    'no-unreachable': 2,
    'no-unused-vars': [2, { 'vars': 'all', 'args': 'none' }],
    'object-curly-spacing': [2, 'always', { 'objectsInObjects': false }],
    'object-shorthand': [2, 'always'],
    'prefer-const': 2,
    'semi': [2, 'always'],
    'use-isnan': 2,
    'valid-typeof': 2,

    'import/export': 2,
    'import/extensions': 2,
    'import/imports-first': 2,
    'import/newline-after-import': 2,
    'import/no-duplicates': 2,
    'import/prefer-default-export': 2,

    'react/jsx-closing-bracket-location': 2,
    'react/jsx-curly-spacing': [2, 'always', { 'spacing': { 'objectLiterals': 'never' }}],
    'react/jsx-indent-props': [2, 2],
    'react/jsx-max-props-per-line': [2, { 'maximum': 2 }],
    'react/jsx-no-bind': 2,
    'react/jsx-no-duplicate-props': 2,
    'react/jsx-no-undef': 2,
    'react/jsx-uses-react': 2,
    'react/jsx-uses-vars': 2,
    'react/jsx-wrap-multilines': 2,
    'react/no-danger': 2,
    'react/no-did-mount-set-state': 2,
    'react/no-did-update-set-state': 2,
    'react/no-direct-mutation-state': 2,
    'react/no-multi-comp': 2,
    'react/no-unknown-property': 2,
    'react/prefer-es6-class': 2,
    'react/prop-types': [2, { ignore: ['children'] }],
    'react/react-in-jsx-scope': 2,
    'react/self-closing-comp': 2,
    'react/sort-comp': [
      2,
      {
        order: [
          'static-methods',
          'lifecycle',
          'everything-else',
          'render'
        ],
        groups: {
          lifecycle: [
            'displayName',
            'propTypes',
            'contextTypes',
            'childContextTypes',
            'mixins',
            'statics',
            'defaultProps',
            'state',
            'getDefaultProps',
            'getInitialState',
            'getChildContext',
            'constructor',
            'componentWillMount',
            'componentDidMount',
            'componentWillReceiveProps',
            'shouldComponentUpdate',
            'componentWillUpdate',
            'componentDidUpdate',
            'componentWillUnmount'
          ]
        }
      }
    ],
    'react/sort-prop-types': 2,
    'react/style-prop-object': 2
  }
};
