const order = [
  'custom-properties',
  'dollar-variables',
  'at-variables',
  'declarations',
  'rules',
  'at-rules'
];

const propertiesOrder = [
  'display',
  'position',
  'top',
  'right',
  'bottom',
  'left',
  'flex',
  'flex-basis',
  'flex-direction',
  'flex-flow',
  'flex-grow',
  'flex-shrink',
  'flex-wrap',
  'align-content',
  'align-items',
  'align-self',
  'justify-content',
  'order',
  'width',
  'min-width',
  'max-width',
  'height',
  'min-height',
  'max-height',
  'margin',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'padding',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  'float',
  'clear',
  'columns',
  'column-gap',
  'column-fill',
  'column-rule',
  'column-span',
  'column-count',
  'column-width',
  'transform',
  'transform-box',
  'transform-origin',
  'transform-style',
  'transition',
  'transition-delay',
  'transition-duration',
  'transition-property',
  'transition-timing-function',
  'border',
  'border-top',
  'border-right',
  'border-bottom',
  'border-left',
  'border-width',
  'border-top-width',
  'border-right-width',
  'border-bottom-width',
  'border-left-width',
  'border-style',
  'border-top-style',
  'border-right-style',
  'border-bottom-style',
  'border-left-style',
  'border-radius',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-bottom-left-radius',
  'border-bottom-right-radius',
  'border-color',
  'border-top-color',
  'border-right-color',
  'border-bottom-color',
  'border-left-color',
  'outline',
  'outline-color',
  'outline-offset',
  'outline-style',
  'outline-width',
  'background',
  'background-attachment',
  'background-color',
  'background-image',
  'background-repeat',
  'background-position',
  'background-size',
  'color',
  'font',
  'font-family',
  'font-size',
  'font-smoothing',
  'font-style',
  'font-variant',
  'font-weight',
  'letter-spacing',
  'line-height',
  'list-style',
  'text-align',
  'text-decoration',
  'text-indent',
  'text-overflow',
  'text-rendering',
  'text-shadow',
  'text-transform',
  'text-wrap',
  'text-size-adjust',
  'white-space',
  'word-spacing',
  'border-collapse',
  'border-spacing',
  'box-shadow',
  'caption-side',
  'content',
  'cursor',
  'empty-cells',
  'opacity',
  'overflow',
  'quotes',
  'speak',
  'table-layout',
  'vertical-align',
  'visibility',
  'z-index',
  'appearance',
  'user-select'
];

const config = {
  'plugins': [
    'stylelint-order'
  ],
  'rules': {
    'at-rule-empty-line-before': ['always', { except: ['after-same-name'] }],
    'at-rule-no-unknown': [true, { ignoreAtRules: ['define-mixin', 'mixin'] }],
    'block-no-empty': true,
    'color-hex-case': 'lower',
    'color-no-invalid-hex': true,
    'declaration-block-no-duplicate-properties': true,
    'declaration-block-no-redundant-longhand-properties': true,
    'declaration-block-no-shorthand-property-overrides': true,
    'declaration-block-trailing-semicolon': 'always',
    'declaration-colon-space-after': 'always',
    'declaration-colon-space-before': 'never',
    'declaration-empty-line-before': 'never',
    'declaration-no-important': true,
    'font-family-name-quotes': 'always-where-recommended',
    'function-comma-space-after': 'always',
    'function-url-quotes': 'always',
    'indentation': [2, { ignore: ['value'] }],
    'length-zero-no-unit': true,
    'max-nesting-depth': [3, { 'ignore': ['blockless-at-rules'] }],
    'media-feature-colon-space-after': 'always',
    'media-feature-colon-space-before': 'never',
    'media-feature-name-no-unknown': true,
    'media-feature-name-no-vendor-prefix': true,
    'no-duplicate-selectors': true,
    'no-extra-semicolons': true,
    'no-missing-end-of-source-newline': true,
    'no-unknown-animations': true,
    'number-leading-zero': 'never',
    'number-no-trailing-zeros': true,
    'order/order': order,
    'order/properties-order': [propertiesOrder, { unspecified: 'bottom' }],
    'property-case': 'lower',
    'property-no-unknown': true,
    'property-no-vendor-prefix': true,
    'rule-empty-line-before': ['always-multi-line', { except: ['first-nested'] }],
    'selector-descendant-combinator-no-non-space': true,
    'selector-list-comma-newline-after': 'always',
    'selector-no-id': true,
    'selector-no-qualifying-type': true,
    'selector-pseudo-class-no-unknown': true,
    'selector-pseudo-element-colon-notation': 'double',
    'selector-pseudo-element-no-unknown': true,
    'selector-type-no-unknown': true,
    'string-no-newline': true,
    'string-quotes': 'double',
    'time-min-milliseconds': 100,
    'unit-case': 'lower',
    'unit-no-unknown': true,
    'value-keyword-case': 'lower',
    'value-no-vendor-prefix': true
  }
};

if (process.argv.find((value, key) => value.includes('stylefmt'))) {
  delete config.rules['order/order'];
}

module.exports = config;
